server:
  servlet:
    context-path: /ministore-api
  port: 8080

spring:
  application:
    name: crud
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jmx:
    enabled: false
  datasource:
    url: jdbc:h2:mem:ministore
    username: root
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console


# PATHS
# http://localhost:8080/ministore-api/h2-console/
