server:
  servlet:
    context-path: /ministore-api
  port: 8081

spring:
  application:
    name: crud
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jmx:
    enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:h2:mem:ministore
    username: root
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

ministore:
  rabbitmq:
    exchange: ministore.exchange
    routingkey: ministore.produto.routingkey

security:
  jwt:
    token:
      secret-key: 3a8382882b7bdf58b7d3abcb3f6aa867

# PATHS
# http://localhost:8081/ministore-api/h2-console/
